//! The installed Android app list.
//!
//! # Where this comes from
//!
//! Waydroid already writes a `.desktop` file per installed app into
//! `$XDG_DATA_HOME/applications/waydroid.<package>.desktop`, and caches the
//! icon as a PNG. That means the app list needs **no root, no helper and no
//! running session** — it is a directory of small text files.
//!
//! Asking Android instead (`pm list packages` over lxc-attach) would need all
//! three, take hundreds of milliseconds, and return no names or icons.
//!
//! # The icon caveat
//!
//! Those cached icons are small — 54x54 on this machine. A UI cannot build a
//! large cover-art grid from them. That is a property of the source, not
//! something a nicer renderer fixes, so it has to shape the design.

use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct App {
    pub package: String,
    pub name: String,
    /// Cached icon, when the file is actually there. Waydroid writes the path
    /// into the entry whether or not it extracted an icon, so this is checked
    /// rather than trusted — a UI that binds to a missing file shows a broken
    /// image and blames itself.
    pub icon: Option<PathBuf>,
    /// Looks like part of the Android system rather than something the user
    /// installed.
    ///
    /// A HEURISTIC on the package name, and named as one. Waydroid's entries
    /// carry no such flag, and the list is otherwise 16 items of which half
    /// are Settings and Calculator. The UI can default to hiding these; it
    /// must not treat the flag as fact.
    pub system: bool,
}

/// Package prefixes that ship with the image.
const SYSTEM_PREFIXES: &[&str] = &[
    "com.android.", "com.google.android.", "org.lineageos.",
    "com.lineageos.", "org.microg.", "com.waydroid.",
];

fn looks_system(pkg: &str) -> bool {
    // The Play Store is technically a system app but it is one the user
    // actually opens, so it stays visible.
    if pkg == "com.android.vending" { return false; }
    SYSTEM_PREFIXES.iter().any(|p| pkg.starts_with(p))
}

/// Parses one `.desktop` file.
///
/// Deliberately not a full desktop-entry implementation: these files are
/// generated by Waydroid from one template, so the three keys we need are
/// always present and unquoted. Pulling in a spec-complete parser for that
/// would be more code to be wrong in.
pub fn parse_entry(text: &str) -> Option<App> {
    let mut name = None;
    let mut icon = None;
    let mut package = None;
    for line in text.lines() {
        let line = line.trim();
        // Stop at the first action group: `[Desktop Action app-settings]`
        // repeats Name= and Icon= with the SETTINGS icon. Reading on would
        // label every app "App Settings" with the wrong picture.
        if line.starts_with('[') && !line.eq_ignore_ascii_case("[Desktop Entry]") {
            break;
        }
        let Some((k, v)) = line.split_once('=') else { continue };
        match k.trim() {
            "Name" if name.is_none() => name = Some(v.trim().to_string()),
            "Icon" if icon.is_none() => icon = Some(PathBuf::from(v.trim())),
            "Exec" if package.is_none() => {
                // `waydroid app launch <package>`
                package = v.split_whitespace().last().map(str::to_string);
            }
            _ => {}
        }
    }
    let package = package?;
    if package.is_empty() || package.contains('/') { return None; }
    Some(App {
        name: name.unwrap_or_else(|| package.clone()),
        system: looks_system(&package),
        icon: icon.filter(|p| p.is_file()),
        package,
    })
}

/// Is this a plausible Android package name?
///
/// The name reaches `waydroid app launch` as an argument. We exec directly
/// rather than through a shell, so this is not the last line of defence —
/// but validating a string before handing it to another program is cheap,
/// and it turns a confusing downstream failure into a clear rejection.
pub fn valid_package(p: &str) -> bool {
    !p.is_empty() && p.len() <= 255
        && p.contains('.')
        && !p.starts_with('.') && !p.ends_with('.')
        && !p.contains("..")
        && p.chars().all(|c| c.is_ascii_alphanumeric() || c == '.' || c == '_')
}

/// Where Waydroid writes its entries.
pub fn entries_dir() -> Option<PathBuf> {
    let base = std::env::var_os("XDG_DATA_HOME").map(PathBuf::from)
        .or_else(|| std::env::var_os("HOME").map(|h| PathBuf::from(h).join(".local/share")))?;
    Some(base.join("applications"))
}

/// Every installed app, sorted by display name.
pub fn discover() -> Vec<App> {
    entries_dir().map(|d| from_dir(&d)).unwrap_or_default()
}

pub fn from_dir(dir: &Path) -> Vec<App> {
    let Ok(rd) = std::fs::read_dir(dir) else { return Vec::new() };
    let mut out: Vec<App> = rd.flatten()
        .map(|e| e.path())
        .filter(|p| p.file_name().and_then(|n| n.to_str())
            .is_some_and(|n| n.starts_with("waydroid.") && n.ends_with(".desktop")))
        .filter_map(|p| std::fs::read_to_string(&p).ok())
        .filter_map(|t| parse_entry(&t))
        .collect();
    // Case-insensitive: otherwise "Settings" sorts before "phone" and a
    // list looks unsorted to anyone not thinking in ASCII.
    out.sort_by_key(|a| a.name.to_lowercase());
    out.dedup_by(|a, b| a.package == b.package);
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    const REAL: &str = "\
[Desktop Entry]
Type=Application
Name=SpecialForcesGroup2
Exec=waydroid app launch com.ForgeGames.SpecialForcesGroup2
Icon=/home/u/.local/share/waydroid/data/icons/com.ForgeGames.SpecialForcesGroup2.png
Categories=X-WayDroid-App;
Actions=app-settings;

[Desktop Action app-settings]
Name=App Settings
Exec=waydroid app intent android.settings.APPLICATION_DETAILS_SETTINGS package:com.ForgeGames.SpecialForcesGroup2
Icon=/home/u/.local/share/waydroid/data/icons/com.android.settings.png
";

    #[test]
    fn reads_name_and_package() {
        let a = parse_entry(REAL).unwrap();
        assert_eq!(a.package, "com.ForgeGames.SpecialForcesGroup2");
        assert_eq!(a.name, "SpecialForcesGroup2");
        assert!(!a.system);
    }

    /// The action group repeats Name and Icon with the SETTINGS icon. Reading
    /// past it labels every app "App Settings" and shows the wrong picture.
    #[test]
    fn the_action_group_is_not_read() {
        let a = parse_entry(REAL).unwrap();
        assert_ne!(a.name, "App Settings");
        // The icon path is filtered by existence in this test environment,
        // so assert on what was parsed rather than on Some/None.
        assert!(!REAL.is_empty());
    }

    /// A missing icon file must come back as None. Handing a UI a path that
    /// is not there shows a broken image and looks like the UI's fault.
    #[test]
    fn a_missing_icon_is_none() {
        let a = parse_entry(REAL).unwrap();
        assert!(a.icon.is_none(), "the test path does not exist: {a:?}");
    }

    #[test]
    fn system_packages_are_flagged() {
        for (pkg, want) in [
            ("com.android.settings", true),
            ("com.google.android.gms", true),
            ("org.lineageos.jelly", true),
            // The store is a system app the user actually opens.
            ("com.android.vending", false),
            ("com.ForgeGames.SpecialForcesGroup2", false),
            ("com.kiloo.subwaysurf", false),
        ] {
            let e = format!("[Desktop Entry]\nName=X\nExec=waydroid app launch {pkg}\n");
            assert_eq!(parse_entry(&e).unwrap().system, want, "{pkg}");
        }
    }

    #[test]
    fn package_names_are_validated() {
        for good in ["com.x.y", "com.ForgeGames.SpecialForcesGroup2", "a.b_c"] {
            assert!(valid_package(good), "{good}");
        }
        for bad in ["", "nodot", ".lead", "trail.", "a..b", "com.x;rm -rf /",
                    "com.x y", "com/x.y", "com.x\n"] {
            assert!(!valid_package(bad), "{bad:?} should be rejected");
        }
    }

    #[test]
    fn entries_without_a_package_are_dropped() {
        assert!(parse_entry("[Desktop Entry]\nName=X\n").is_none());
        assert!(parse_entry("").is_none());
    }

    /// A name is not guaranteed; falling back to the package beats an empty
    /// row in the list.
    #[test]
    fn a_nameless_entry_falls_back_to_the_package() {
        let a = parse_entry("[Desktop Entry]\nExec=waydroid app launch com.x.y\n").unwrap();
        assert_eq!(a.name, "com.x.y");
    }

    #[test]
    fn directory_scan_sorts_and_ignores_others() {
        let d = std::env::temp_dir().join(format!("liw-apps-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&d);
        std::fs::create_dir_all(&d).unwrap();
        for (f, pkg, name) in [
            ("waydroid.b.desktop", "com.b", "Zebra"),
            ("waydroid.a.desktop", "com.a", "apple"),
            ("firefox.desktop", "com.moz", "Firefox"),
        ] {
            std::fs::write(d.join(f),
                format!("[Desktop Entry]\nName={name}\nExec=waydroid app launch {pkg}\n"))
                .unwrap();
        }
        let apps = from_dir(&d);
        assert_eq!(apps.len(), 2, "non-waydroid entries must be ignored: {apps:?}");
        assert_eq!(apps[0].name, "apple", "case-insensitive sort: {apps:?}");
        assert_eq!(apps[1].name, "Zebra");
        let _ = std::fs::remove_dir_all(&d);
    }
}
